remote_theme: dieghernan/chulapa

title: SCP-017
subtitle: Private Portfolio

navbar:
  style: "classic"
  brand:
    title: Home
    img: "https://is.gd/5QfbUt"
  nav:
  - title: ReVanced
    child:
     - title: Info
       url: /revanced/home

     - title: microG
       url: /revanced/micro-g

     - title: Nyx Music Player
       url: /revanced/nyx

     - title: Reddit
       url: /revanced/reddit

     - title: ReVanced Manager
       url: /revanced/revanced.manager

     - title: Spotify
       url: /revanced/spotify

     - title: TikTok
       url: /revanced/tiktok

     - title: Twitch
       url: /revanced/twitch

     - title: Twitter
       url: /revanced/twitter

     - title: YouTube
       url: /revanced/youtube

     - title: YouTube Music
       url: /revanced/youtube.music

footer:
  links:
    - label : Facebook
      icon  : fab fa-facebook
      url   : https://fb.me/fb.me.2
    - label : GitHub
      icon  : fab fa-github
      url   : https://github.com/SCP-017
    - label : Proton Mail
      icon  : fa fa-envelope-o
      url   : ph.server@pm.me
  copyright: © 2022 by SCP-017

chulapa-skin: 
  skin: twitter-lights-out

#### Defaults (Do not modify.)
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      header_type: "base"
      include_on_search   : false
      cloudtag_url        : "/tags"
      cloudcategory_url   : "/categories"

  -
    scope:
      path: ""
      type: "posts"
    values:
      header_type       : "post"
      include_on_search : true
      include_on_feed   : true
      show_date         : true
      show_bottomnavs   : true
      show_sociallinks  : true
      show_comments     : true
      show_tags         : true
      show_categories   : true
      show_author       : true
      show_toc          : false
  -
    scope:
      path: ""
      type: "demo"
    values:
      header_type       : "hero"
      show_bottomnavs   : true
      show_sociallinks  : true
      include_on_search : true
      include_on_feed   : true

compress_html:
  clippings: all
  blanklines: true

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap

exclude:
  - LICENSE
  - readme.md
  - Gemfile
  - vendor

include:
 - _pages

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  footnote_backlink: '&uarr;'
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
  sass_dir: _sass
  style: compressed
