remote_theme: dieghernan/chulapa

title: SCP-017
subtitle: Private Portfolio

navbar:
  style: "classic"
  brand:
    title: Home
    img: "https://is.gd/5QfbUt"
  nav:
  - title: ReVanced
    child:
     - title: Info
       url: /pages/revanced/home
     - title: microG (Fork)
       url: /pages/revanced/micro-g
     - title: Nyx Music Player
       url: /pages/revanced/nyx
     - title: Reddit
       url: /pages/revanced/reddit
     - title: ReVanced Manager
       url: /pages/revanced/revanced.manager
     - title: Spotify
       url: /pages/revanced/spotify
     - title: TikTok
       url: /pages/revanced/tiktok
     - title: Twitch
       url: /pages/revanced/twitch
     - title: Twitter
       url: /pages/revanced/twitter
     - title: YouTube
       url: /pages/revanced/youtube
     - title: YouTube Music
       url: /pages/revanced/youtube.music

  - title: Alternatives
    child:
     - title: CloudStream
       url: /pages/alternatives/cloud.stream
     - title: Infinity for Reddit
       url: /pages/alternatives/infinity.for.reddit
     - title: xManager-Spotify
       url: /pages/alternatives/x.manager.spotify

  - title: Stream Music
    child:
     - title: Stream Lofi Girl
       url: /pages/misc/stream.music/lofi.girl
     - title: Stream NCS Arcade
       url: /pages/misc/stream.music/ncs.arcade
     - title: Stream Nostalgic
       url: /pages/misc/stream.music/nostalgic
     - title: Stream SpongeBoy Lofi
       url: /pages/misc/stream.music/spongeboy.lofi
     - title: Stream The Bootleg Boy 2
       url: /pages/misc/stream.music/the.bootleg.boy.2

footer:
  links:
    - label : Facebook
      icon  : fab fa-facebook
      url   : https://fb.me/fb.me.2
    - label : GitHub
      icon  : fab fa-github
      url   : https://github.com/SCP-017
    - label : Proton Mail
      icon  : fa fa-envelope
      url   : ph.server@pm.me
  copyright: © 2022 by SCP-017

chulapa-skin: 
  skin: twitter-lights-out

comments:
  provider: giscus #https://giscus.app

#  provider: disqus #https://disqus.com
#  disqus_shortname: scp-017

#### Defaults (Do not modify.)
collections:
  myposts:
    output: true
    permalink: /myposts/:name
collections_dir     : collections

permalink           : /:year:month:day_:title/
paginate: 4
paginate_path: "/blog/page:num/"
paginator_maxnum: 3 

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      header_type         : "base"
      include_on_search   : false
  -
    scope:
      path: ""
      type: "myposts"
    values:
      header_type: "post"
      include_on_search   : false
      show_comments     : true

compress_html:
  clippings: all
  blanklines: true

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap

exclude:
  - LICENSE
  - readme.md
  - Gemfile
  - vendor

include:
 - _pages

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  footnote_backlink: '&uarr;'
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
  sass_dir: _sass
  style: compressed
