remote_theme: dieghernan/chulapa

title: SCP-017
subtitle: Private Website

author:
  name                  :      SCP-017
  avatar                :      https://avatars.githubusercontent.com/u/112224835
  location              :      SCP Foundation (Site-19)
  links:                
    - url: https://fb.me/fb.me.2
      icon: "fab fa-facebook"
    - url: https://github.com/SCP-017
      icon: "fab fa-github"
    - url: ph.server@pm.me
      icon: "fa fa-envelope"

navbar:
  style: "classic"
  brand:
    title: Home
    img: "https://avatars.githubusercontent.com/u/112224835"
  nav:
  - title: My Posts
    url: /pages/index.pages/my.posts

  - title: ReVanced
    child:
     - title: Home Info
       url: /pages/revanced/home
     - title: Home Info
       url:  /pages/index.pages/revanced

  - title: Alternatives
    child:
     - title: CloudStream
       url: /pages/alternatives/cloud.stream
     - title: Infinity for Reddit
       url: /pages/alternatives/infinity.for.reddit
     - title: xManager-Spotify
       url: /pages/alternatives/x.manager.spotify

  - title: Stream Music
    child:
     - title: Stream Lofi Geek
       url: /pages/misc/stream.music/lofi.geek
     - title: Stream Lofi Girl
       url: /pages/misc/stream.music/lofi.girl
     - title: Stream NCS Arcade
       url: /pages/misc/stream.music/ncs.arcade
     - title: Stream SpongeBoy Lofi
       url: /pages/misc/stream.music/spongeboy.lofi
     - title: Stream The Bootleg Boy 2
       url: /pages/misc/stream.music/the.bootleg.boy.2

  - title: Info
    child:
     - title: About Me
       url: /pages/info/aboutme

footer:
  links:
    - label : Facebook
      icon  : fab fa-facebook
      url   : https://fb.me/fb.me.2
    - label : GitHub
      icon  : fab fa-github
      url   : https://github.com/SCP-017
    - label : Proton Mail
      icon  : fa fa-envelope
      url   : ph.server@pm.me
  copyright: © 2022 by SCP-017

googlefonts:
 - url: https://fonts.googleapis.com/css2?family=Ubuntu+Mono&display=swap

chulapa-skin: 
  skin: twitter-lights-out
  vars:
    font-family-base: "Ubuntu Mono"

comments:
  provider: giscus #https://giscus.app

#  provider: disqus #https://disqus.com
#  disqus_shortname: scp-017

#### Defaults (Do not modify.)
# Collections path where you place your posts. (ex. pages/collections/_my.posts/post1.md)
collections:
  my.posts:
    output: true
    permalink: /my.posts/:name
  revanced:
    output: true
    permalink: /revanced/:name

# Collections directory path. (ex. pages/collections or yourpreferredname/yourpreferredname)
collections_dir     : pages/_collections

defaults:
  -
    scope:
      path: ""
    values:
      layout: "minimal"
      include_on_search : false
      show_comments     : true
  -
    scope:
      path: "pages/index.pages"
    values:
      layout: "indexcategory"
      show_comments     : false
      header_type       : "base"
      header_img        : assets/images/webpage/galaxy.forest.jpg
  -
    scope:
      path: "pages/_collections/_my.posts"
    values:
      layout: "default"
      header_type       : "post"
      show_author       : true
      header_img        : assets/images/webpage/red.black.hole.jpg
  -
    scope:
      path: "pages/_collections/_revanced"
    values:
      layout: "default"
      header_type       : "post"
      show_author       : true
      header_img        : assets/images/webpage/red.black.hole.jpg

compress_html:
  clippings: all
  blanklines: true

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap

exclude:
  - LICENSE
  - readme.md
  - Gemfile
  - vendor

markdown: kramdown
highlighter: github
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  footnote_backlink: '&uarr;'
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
  sass_dir: _sass
  style: compressed
