name: Get Changelogs

on:
  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Checkout
      uses: actions/checkout@main

    - name: Copy Files
      run: |
        cd pages/scripts
        chmod +x patches.changelog.py
        python patches.changelog.py

    - name: Commit to the repo
      run: |
        git config --global user.name "SCP-017"
        git config --global user.email "unbug.ph@gmail.com"
        git add .
        git commit -am "Update Changelogs"
        git push
