name: Get Changelogs

on:
  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Checkout
      uses: actions/checkout@main

    - name: Copy Files
      run: |
        cd pages/scripts
        chmod +x patches.changelog.py
        python patches.changelog.py
